/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddScheduleRouteImport } from './routes/add-schedule'
import { Route as FreePeriodsRouteImport } from './routes/free-periods'
import { Route as OverlapRouteImport } from './routes/overlap'
import { Route as StudentStudentIdRouteImport } from './routes/student.$studentId'
import { Route as ApiPublicExtractScheduleRouteImport } from './routes/api/public/extract-schedule'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddScheduleRoute = AddScheduleRouteImport.update({
  id: '/add-schedule',
  path: '/add-schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const FreePeriodsRoute = FreePeriodsRouteImport.update({
  id: '/free-periods',
  path: '/free-periods',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlapRoute = OverlapRouteImport.update({
  id: '/overlap',
  path: '/overlap',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentStudentIdRoute = StudentStudentIdRouteImport.update({
  id: '/student/$studentId',
  path: '/student/$studentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExtractScheduleRoute =
  ApiPublicExtractScheduleRouteImport.update({
    id: '/api/public/extract-schedule',
    path: '/api/public/extract-schedule',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-schedule': typeof AddScheduleRoute
  '/free-periods': typeof FreePeriodsRoute
  '/overlap': typeof OverlapRoute
  '/student/$studentId': typeof StudentStudentIdRoute
  '/api/public/extract-schedule': typeof ApiPublicExtractScheduleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-schedule': typeof AddScheduleRoute
  '/free-periods': typeof FreePeriodsRoute
  '/overlap': typeof OverlapRoute
  '/student/$studentId': typeof StudentStudentIdRoute
  '/api/public/extract-schedule': typeof ApiPublicExtractScheduleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-schedule': typeof AddScheduleRoute
  '/free-periods': typeof FreePeriodsRoute
  '/overlap': typeof OverlapRoute
  '/student/$studentId': typeof StudentStudentIdRoute
  '/api/public/extract-schedule': typeof ApiPublicExtractScheduleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-schedule'
    | '/free-periods'
    | '/overlap'
    | '/student/$studentId'
    | '/api/public/extract-schedule'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-schedule'
    | '/free-periods'
    | '/overlap'
    | '/student/$studentId'
    | '/api/public/extract-schedule'
  id:
    | '__root__'
    | '/'
    | '/add-schedule'
    | '/free-periods'
    | '/overlap'
    | '/student/$studentId'
    | '/api/public/extract-schedule'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddScheduleRoute: typeof AddScheduleRoute
  FreePeriodsRoute: typeof FreePeriodsRoute
  OverlapRoute: typeof OverlapRoute
  StudentStudentIdRoute: typeof StudentStudentIdRoute
  ApiPublicExtractScheduleRoute: typeof ApiPublicExtractScheduleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-schedule': {
      id: '/add-schedule'
      path: '/add-schedule'
      fullPath: '/add-schedule'
      preLoaderRoute: typeof AddScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-periods': {
      id: '/free-periods'
      path: '/free-periods'
      fullPath: '/free-periods'
      preLoaderRoute: typeof FreePeriodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlap': {
      id: '/overlap'
      path: '/overlap'
      fullPath: '/overlap'
      preLoaderRoute: typeof OverlapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/$studentId': {
      id: '/student/$studentId'
      path: '/student/$studentId'
      fullPath: '/student/$studentId'
      preLoaderRoute: typeof StudentStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extract-schedule': {
      id: '/api/public/extract-schedule'
      path: '/api/public/extract-schedule'
      fullPath: '/api/public/extract-schedule'
      preLoaderRoute: typeof ApiPublicExtractScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddScheduleRoute: AddScheduleRoute,
  FreePeriodsRoute: FreePeriodsRoute,
  OverlapRoute: OverlapRoute,
  StudentStudentIdRoute: StudentStudentIdRoute,
  ApiPublicExtractScheduleRoute: ApiPublicExtractScheduleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
