/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FreePeriodsRouteImport } from './routes/free-periods'
import { Route as StudentStudentIdRouteImport } from './routes/student.$studentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FreePeriodsRoute = FreePeriodsRouteImport.update({
  id: '/free-periods',
  path: '/free-periods',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentStudentIdRoute = StudentStudentIdRouteImport.update({
  id: '/student/$studentId',
  path: '/student/$studentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/free-periods': typeof FreePeriodsRoute
  '/student/$studentId': typeof StudentStudentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/free-periods': typeof FreePeriodsRoute
  '/student/$studentId': typeof StudentStudentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/free-periods': typeof FreePeriodsRoute
  '/student/$studentId': typeof StudentStudentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/free-periods' | '/student/$studentId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/free-periods' | '/student/$studentId'
  id: '__root__' | '/' | '/free-periods' | '/student/$studentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FreePeriodsRoute: typeof FreePeriodsRoute
  StudentStudentIdRoute: typeof StudentStudentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-periods': {
      id: '/free-periods'
      path: '/free-periods'
      fullPath: '/free-periods'
      preLoaderRoute: typeof FreePeriodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/$studentId': {
      id: '/student/$studentId'
      path: '/student/$studentId'
      fullPath: '/student/$studentId'
      preLoaderRoute: typeof StudentStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FreePeriodsRoute: FreePeriodsRoute,
  StudentStudentIdRoute: StudentStudentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
